# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.17
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-
      - run:
          name: yarn install
          command: 'yarn install --pure-lockfile --no-progress'
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn test
      - run:
          name: Create directories for Artifacts
          command: mkdir -p ~/artifacts/scalyr_plugin/
      - run: 
          name: Build artifacts
          command: |
            yarn build
            cp -rf dist/ ~/artifacts/scalyr_plugin/
      - persist_to_workspace:
          root: ~/artifacts/scalyr_plugin
          paths:
            - dist
      - store_artifacts:
          path: ~/artifacts/scalyr_plugin
          destination: scalyr_grafana_plugin
  
  deploy-to-github-releases:
    docker: 
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: ~/artifacts/scalyr_plugin/
      - run:
          name: List dir 
          command: ls ~/artifacts/scalyr_plugin/dist/
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=1.0.1
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /home/circleci/artifacts/scalyr_plugin/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-to-github-releases:
          requires:
            - build
          filters:
            branches:
              only: feature/circleci
        