# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
aliases:
  # Workflow filters
  - &filter-not-release-or-master
    tags:
      ignore: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
    branches:
      ignore:
        - master
  - &filter-only-master
    branches:
      only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.17
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-
      - run:
          name: yarn install
          command: 'yarn install --pure-lockfile --no-progress'
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn build

# TODO: Ship dist/ folder to github releases and tag them
